# PyTorch 基础示例

这个 notebook 演示了 PyTorch 的基本用法，包括：
1. 导入库
2. 创建张量
3. 基本运算
4. 简单的神经网络

In [6]:
# 导入必要的库
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np

# 检查 PyTorch 版本和 CUDA 可用性
print(f"PyTorch 版本: {torch.__version__}")
print(f"CUDA 可用: {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"CUDA 设备数量: {torch.cuda.device_count()}")
    print(f"当前 CUDA 设备: {torch.cuda.get_device_name(0)}")

PyTorch 版本: 2.7.1+cpu
CUDA 可用: False


In [2]:
# 1. 创建张量 (Tensors)
print("=== 创建张量 ===")

# 创建不同类型的张量
x = torch.tensor([1, 2, 3, 4, 5])
print(f"一维张量: {x}")

y = torch.zeros(2, 3)
print(f"零矩阵: \n{y}")

z = torch.randn(2, 3)
print(f"随机矩阵: \n{z}")

# 从 NumPy 数组创建张量
np_array = np.array([1, 2, 3])
tensor_from_np = torch.from_numpy(np_array)
print(f"从 NumPy 创建: {tensor_from_np}")

=== 创建张量 ===
一维张量: tensor([1, 2, 3, 4, 5])
零矩阵: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])
随机矩阵: 
tensor([[ 0.6303, -0.5816,  1.4562],
        [ 1.6320,  1.7117,  0.0891]])
从 NumPy 创建: tensor([1, 2, 3])


In [3]:
# 2. 张量基本运算
print("=== 张量运算 ===")

a = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
b = torch.tensor([[5, 6], [7, 8]], dtype=torch.float32)

print(f"矩阵 a: \n{a}")
print(f"矩阵 b: \n{b}")

# 加法
c = a + b
print(f"a + b: \n{c}")

# 矩阵乘法
d = torch.mm(a, b)
print(f"a @ b (矩阵乘法): \n{d}")

# 元素级乘法
e = a * b
print(f"a * b (元素级乘法): \n{e}")

# 求和、均值等
print(f"a 的和: {a.sum()}")
print(f"a 的均值: {a.mean()}")

=== 张量运算 ===
矩阵 a: 
tensor([[1., 2.],
        [3., 4.]])
矩阵 b: 
tensor([[5., 6.],
        [7., 8.]])
a + b: 
tensor([[ 6.,  8.],
        [10., 12.]])
a @ b (矩阵乘法): 
tensor([[19., 22.],
        [43., 50.]])
a * b (元素级乘法): 
tensor([[ 5., 12.],
        [21., 32.]])
a 的和: 10.0
a 的均值: 2.5


In [4]:
# 3. 自动梯度 (Autograd)
print("=== 自动梯度计算 ===")

# 创建需要梯度的张量
x = torch.tensor([2.0, 3.0], requires_grad=True)
print(f"输入 x: {x}")

# 定义一个简单的函数: y = x^2 + 2x + 1
y = x**2 + 2*x + 1
print(f"y = x^2 + 2x + 1: {y}")

# 计算 y 的和
z = y.sum()
print(f"z = sum(y): {z}")

# 反向传播计算梯度
z.backward()
print(f"x 的梯度 (dz/dx): {x.grad}")

# 验证: dy/dx = 2x + 2，在 x=[2,3] 处应该是 [6, 8]
print(f"理论梯度 (2x + 2): {2*x.data + 2}")

=== 自动梯度计算 ===
输入 x: tensor([2., 3.], requires_grad=True)
y = x^2 + 2x + 1: tensor([ 9., 16.], grad_fn=<AddBackward0>)
z = sum(y): 25.0
x 的梯度 (dz/dx): tensor([6., 8.])
理论梯度 (2x + 2): tensor([6., 8.])


In [5]:
# 4. 简单的神经网络
print("=== 简单神经网络 ===")

# 定义一个简单的线性模型
class SimpleNet(nn.Module):
    def __init__(self):
        super(SimpleNet, self).__init__()
        self.linear1 = nn.Linear(2, 4)  # 输入层到隐藏层
        self.linear2 = nn.Linear(4, 1)  # 隐藏层到输出层
    
    def forward(self, x):
        x = F.relu(self.linear1(x))  # ReLU 激活函数
        x = self.linear2(x)
        return x

# 创建模型实例
model = SimpleNet()
print(f"模型结构: \n{model}")

# 创建一些示例数据
input_data = torch.randn(5, 2)  # 5 个样本，每个样本 2 个特征
print(f"输入数据: \n{input_data}")

# 前向传播
output = model(input_data)
print(f"模型输出: \n{output}")

# 显示模型参数
print("\n模型参数:")
for name, param in model.named_parameters():
    print(f"{name}: {param.shape}")

=== 简单神经网络 ===
模型结构: 
SimpleNet(
  (linear1): Linear(in_features=2, out_features=4, bias=True)
  (linear2): Linear(in_features=4, out_features=1, bias=True)
)
输入数据: 
tensor([[ 0.0923, -1.2550],
        [ 0.5273,  0.5189],
        [ 0.4878,  1.9061],
        [-0.3961,  0.6482],
        [-0.6711, -1.7413]])
模型输出: 
tensor([[0.3551],
        [0.5018],
        [0.5758],
        [0.4384],
        [0.2894]], grad_fn=<AddmmBackward0>)

模型参数:
linear1.weight: torch.Size([4, 2])
linear1.bias: torch.Size([4])
linear2.weight: torch.Size([1, 4])
linear2.bias: torch.Size([1])
